stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    params:
    - prepare.path_fetures
    - prepare.path_edges
    - prepare.path_classes
    outs:
    - src/prepared
  dataset:
    cmd: python src/dataset.py
    deps:
    - src/dataset.py
    - src/prepared
    params:
    - dataset.path_classes
    - dataset.path_edgelist_timed
    - dataset.path_fetures
    - dataset.path_nodetime
    - dataset.path_merged_nodes
    - dataset.path_node_label
    outs:
    - src/dataset
  model:
    cmd: python src/model.py
    deps:
    - src/dataset
    params:
    - model.num_node_features
    - model.hidden_channels
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - src/model.py
    params:
    - train.patience
    - train.lr
    - train.epoches
    - train.path_train_loader
    - train.path_test_loader
    plots:
      - training_loss_acc.json:
          cache: false
          x: epoch
          y: 
            train_loss
            val_loss

    outs:
    - src/model
  # evaluate:
  #   cmd: python src/evaluate.py
  #   deps:
  #   - src/evaluate.py
  #   # - src/model
  #   # - src/generated
  #   params:
  #   - evaluate.data_train
  #   - evaluate.model_state
  #   metrics:
  #   - test_acc.json:
  #       cache: false