prepare:
  path_fetures: 'data/elliptic_txs_features.csv'
  path_edges: 'data/elliptic_txs_edgelist.csv'
  path_classes: 'data/elliptic_txs_classes.csv'
dataset:
  path_classes: 'src/prepared/elliptic_txs_classes.csv'
  path_edgelist_timed: 'src/prepared/elliptic_txs_edgelist_timed.csv'
  path_fetures: 'src/prepared/elliptic_txs_features.csv'
  path_nodetime: 'src/prepared/elliptic_txs_nodetime.csv'
  path_merged_nodes: 'src/prepared/merged_nodes_df.csv'
  path_node_label: 'src/prepared/node_label.csv'  
model:
  num_node_features: 166
  hidden_channels: [100]
  dropout: 0.5
train:
  patience: 50
  lr: 0.001
  epoches: 1000
  path_train_loader: "src/dataset/train_loader.pth"
  path_test_loader: "src/dataset/test_loader.pth"